name: Build signed apk artifact

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build_signed_apl:
    name: Build and sign apk
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Checkout keystore repo
        uses: actions/checkout@v2
        with:
          repository: ${{ secrets.KEYSTORE_GIT_REPOSITORY }}
          token: ${{ secrets.KEYSTORE_ACCESS_TOKEN }}
          path: ./key

      - name: Move keyfiles
        run: mv ./key/*.* ./

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build and sign APK with Gradle
        run: |
          ./gradlew assembleRelease --stacktrace
          ./gradlew bundleRelease

      - name: Upload signed APK
        uses: actions/upload-artifact@v2
        with:
          name: Fingen
          path: ./app/build/outputs/apk/prod/release/app-prod-release.apk